// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKe1Ha9MZXPfByhArqC_zo6nNhneiKTAk',
    appId: '1:121382459364:web:112acc29aae1f0874959f1',
    messagingSenderId: '121382459364',
    projectId: 'chatzilla-2eb30',
    authDomain: 'chatzilla-2eb30.firebaseapp.com',
    storageBucket: 'chatzilla-2eb30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjS5E5yqch7qzhxciPBnFiPkATknY6AbU',
    appId: '1:121382459364:android:2660a83b6734dfa54959f1',
    messagingSenderId: '121382459364',
    projectId: 'chatzilla-2eb30',
    storageBucket: 'chatzilla-2eb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5BaCPOCQwzkJkPh4K05kFuI1XPEhJSpw',
    appId: '1:121382459364:ios:26f341bad17f11974959f1',
    messagingSenderId: '121382459364',
    projectId: 'chatzilla-2eb30',
    storageBucket: 'chatzilla-2eb30.firebasestorage.app',
    iosBundleId: 'com.example.chatzilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5BaCPOCQwzkJkPh4K05kFuI1XPEhJSpw',
    appId: '1:121382459364:ios:26f341bad17f11974959f1',
    messagingSenderId: '121382459364',
    projectId: 'chatzilla-2eb30',
    storageBucket: 'chatzilla-2eb30.firebasestorage.app',
    iosBundleId: 'com.example.chatzilla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKe1Ha9MZXPfByhArqC_zo6nNhneiKTAk',
    appId: '1:121382459364:web:fac2a8822d4498894959f1',
    messagingSenderId: '121382459364',
    projectId: 'chatzilla-2eb30',
    authDomain: 'chatzilla-2eb30.firebaseapp.com',
    storageBucket: 'chatzilla-2eb30.firebasestorage.app',
  );

}